SELECT
    R.REST_ID,
    R.REST_NAME,
    R.FOOD_TYPE,
    R.FAVORITES,
    R.ADDRESS,
    ROUND(AVG(REV.REVIEW_SCORE), 2) AS SCORE
FROM
    REST_INFO R
JOIN
    REST_REVIEW REV
ON
    R.REST_ID = REV.REST_ID
WHERE
    R.ADDRESS LIKE '서울%'
GROUP BY
    R.REST_ID
ORDER BY
    SCORE DESC,
    R.FAVORITES DESC;
